### ISSUE TITLE
KeyError: '14d5adfe50bb4445bc3aa5fe607691a8' in preprocessing

### ISSUE THREAD

**Issue by ZeweiZhou** [nvr-avg/ScePT#2]
Hi！
I am very interested in your amazing work, but there is a KeyError in the preprocessing. Are there some errors in dataset setting? Wish your response !

`(ScePT) root@ScePT-main/experiments/nuScenes# python process_data.py --data=./v1.0-mini --version="v1.0-mini" --output_path=../processed --num_worker=1`
`======`
`Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map, `
`Done loading in 0.568 seconds.`
`======`
`Reverse indexing ...
Done reverse indexing in 0.1 seconds.`
`======`
`Preprocessing train_val Samples:   0%|                                                                                                                       | 0/8560 [00:00<?, ?it/s]`
`Traceback (most recent call last):`
  `File "process_data.py", line 755, in <module>
    process_data(args.data, args.version, args.output_path, args.num_workers)`
  `File "process_data.py", line 664, in process_data
    samples = aggregate_samples(`
  `File "process_data.py", line 225, in aggregate_samples
    sample = nusc.get("sample", start)`
  `File "/root/miniconda3/envs/ScePT/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 207, in get
    return getattr(self, table_name)[self.getind(table_name, token)]`
  `File "/root/miniconda3/envs/ScePT/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 216, in getind
    return self._token2ind[table_name][token]`
`KeyError: '14d5adfe50bb4445bc3aa5fe607691a8'`

**Comment by chenyx09** [comment]
This is a commonly seen bug, in line 634 of process_data.py, you need to
select the right data portion of nuScenes.

**Comment by ZeweiZhou** [comment]
Thanks a lot!
